# Užduotys
**Atkreipkite dėmesį, kad, jeigu neteisingai įvsite atsakymą, Out reikšmė irgi pasikeis**

In [5]:
import numpy as np

1\. Sukurkite vektorių su skaičiais nuo 1 iki 9

In [4]:
vektorius = [1:, 10]
masyvas = np.array(vektorius)
print(vektorius)

SyntaxError: invalid syntax (711381466.py, line 1)

In [6]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2\. Sukurkite vektorių iš 10 nulių

In [7]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3\. Sukurkite vektorių iš 10 vienetų

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4\. Sukurkite vektorių iš 10 ketvertų

In [10]:
np.fours(10)

AttributeError: module 'numpy' has no attribute 'fours'

In [11]:
np.ones(10) * 4


array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

5\. Sukurkite vektorių iš lyginių skaičių nuo 0 iki 100

In [12]:
np.array(100) %= 2

SyntaxError: 'function call' is an illegal expression for augmented assignment (2952936911.py, line 1)

In [13]:
np.arange(0, 100, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

6\. Sukurkite matricą iš 25 narių, pradedant 1, baigiant 25. Priskirkite ją kintamąjam.

In [20]:
mas = np.arange(1, 26).reshape(5, 5)
print(mas)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [22]:
mas = np.arange(1, 26)
print(mas)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [24]:
mas = np.reshape(5, 6)
print(mas)

ValueError: cannot reshape array of size 1 into shape (6,)

In [27]:
mas = np.arange(1, 26).reshape(5, 5)
print(mas)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


7\. Iš matricos ištraukite skaičių 12

In [31]:
sk_12 = mas[2, 1]
print(sk_12)

12


In [34]:
sk_19 = mas[3, 3]
print(sk_19)

19


8\. Iš matricos ištraukite paskutinę eilutę.

In [38]:
be_paskutines_eilutes = mas[:-1]
print(be_paskutines_eilutes)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [39]:
paskutine_eilute = mas[-1]
print(paskutine_eilute)

[21 22 23 24 25]


9\. Iš matricos ištraukite submatricą

1, 2, 3  
6, 7, 8  
11,12,13

In [63]:
masyvas = np.concatenate((np.arange(1, 4), np.arange(6, 9), np.arange(11, 14)))
print(masyvas)


[ 1  2  3  6  7  8 11 12 13]


In [61]:
masyvas.reshape(3,3)

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [65]:
mas = np.arange(1, 26).reshape(5, 5)
print(mas)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [83]:
mas

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [67]:
mas[:3, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

10\. Iš matricos ištraukite submatricą

7, 8, 9, 10  
12, 13, 14, 15  
17, 18, 19, 20

In [73]:
mas[1:4, 1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

11\. Iš matricos ištraukite submatricą

16, 17, 18  
21, 22, 23

In [77]:
mas[3:, :3]

array([[16, 17, 18],
       [21, 22, 23]])

12\. Sukurkite vektorių iš 20 atsitiktinių reikšmių nuo 0 iki 1. Priskirkite kintamąjam.

In [78]:
masrand = np.random.rand(20)



In [82]:
masrand


array([0.8269187 , 0.84967029, 0.42205826, 0.07002806, 0.87102212,
       0.78136161, 0.10670154, 0.26704715, 0.71714197, 0.92509406,
       0.560087  , 0.27613227, 0.14950805, 0.50620062, 0.68716193,
       0.60468734, 0.76435611, 0.84488725, 0.703891  , 0.88268604])

In [81]:
print(masrand)

[0.8269187  0.84967029 0.42205826 0.07002806 0.87102212 0.78136161
 0.10670154 0.26704715 0.71714197 0.92509406 0.560087   0.27613227
 0.14950805 0.50620062 0.68716193 0.60468734 0.76435611 0.84488725
 0.703891   0.88268604]


13\. Suraskite didžiausią reikšmę masyve ir jos indeksą.

In [84]:
max(masrand)

0.9250940597285726

In [87]:
masrand.argmax() + 1    #indeksas prasidedantis nuo 1, ne nulio

10

14\. Suraskite mažiausią reikšmę ir jos indeksą

In [88]:
min(masrand)

0.07002805777758381

In [92]:
masrand.argmin()

3

masrand.argmin()

15\. Atspausdinkite šios matricos duomenų tipą

In [94]:
masrand.dtype

dtype('float64')

16\. Sukurkite vektorių iš integer reikšmių nuo 1 iki 100. Priskirkite kintamąjam. Iš jo ištraukite visus skaičius, didesnius už 90

In [99]:
mase = np.arange(1, 101).reshape(10,10)
mase


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [101]:
mase > 90

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [102]:
mase[mase>90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

17\. Ištraukite iš vektoriaus visus skaičiaus 7 kartotinius

In [105]:
mase[mase % 7 ==0]



array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [107]:
mase[mase // 7 == 0]

array([1, 2, 3, 4, 5, 6])

In [108]:
mase[mase / 7 ==0]

array([], dtype=int32)

18\. Sukurkite tokią matricą:

In [55]:
# array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
#        [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
#        [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
#        [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
#        [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])


array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

19\. sukurkite tokią matricą (sveiki sk. nuo 2 iki 1000 iš kurių traukiasi sveika šaknis):

In [74]:
# array([[  4,   9,  16,  25,  36],
#        [ 49,  64,  81, 100, 121],
#        [144, 169, 196, 225, 256],
#        [289, 324, 361, 400, 441],
#        [484, 529, 576, 625, 676],
#        [729, 784, 841, 900, 961]])

In [6]:
naujas_masyvas = np.linspace(0.025,1).reshape(5,8) #pagal nutylejima generuoja 50

ValueError: cannot reshape array of size 50 into shape (5,8)

In [7]:
naujas_masyvas = np.linspace(0.025,1).reshape(5,-1)
naujas_masyvas

array([[0.025     , 0.04489796, 0.06479592, 0.08469388, 0.10459184,
        0.1244898 , 0.14438776, 0.16428571, 0.18418367, 0.20408163],
       [0.22397959, 0.24387755, 0.26377551, 0.28367347, 0.30357143,
        0.32346939, 0.34336735, 0.36326531, 0.38316327, 0.40306122],
       [0.42295918, 0.44285714, 0.4627551 , 0.48265306, 0.50255102,
        0.52244898, 0.54234694, 0.5622449 , 0.58214286, 0.60204082],
       [0.62193878, 0.64183673, 0.66173469, 0.68163265, 0.70153061,
        0.72142857, 0.74132653, 0.76122449, 0.78112245, 0.80102041],
       [0.82091837, 0.84081633, 0.86071429, 0.88061224, 0.9005102 ,
        0.92040816, 0.94030612, 0.96020408, 0.98010204, 1.        ]])

In [8]:
elementu_skaicius_masyve = naujas_masyvas.size #parodo kiek elementu masyve
print(elementu_skaicius_masyve)

50


In [141]:
np.linspace(0.025,1, 40).reshape(5,8)

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [120]:
tukstantinis = np.arange(2, 1001)

In [136]:
np.linspace(0.025,1).reshape(-1,5)  #galima nenurodyti tik 1 "reshape" formato.
                                    #"-1" yra tas, kuris vadinamas "nenurodytu"

array([[0.025     , 0.04489796, 0.06479592, 0.08469388, 0.10459184],
       [0.1244898 , 0.14438776, 0.16428571, 0.18418367, 0.20408163],
       [0.22397959, 0.24387755, 0.26377551, 0.28367347, 0.30357143],
       [0.32346939, 0.34336735, 0.36326531, 0.38316327, 0.40306122],
       [0.42295918, 0.44285714, 0.4627551 , 0.48265306, 0.50255102],
       [0.52244898, 0.54234694, 0.5622449 , 0.58214286, 0.60204082],
       [0.62193878, 0.64183673, 0.66173469, 0.68163265, 0.70153061],
       [0.72142857, 0.74132653, 0.76122449, 0.78112245, 0.80102041],
       [0.82091837, 0.84081633, 0.86071429, 0.88061224, 0.9005102 ],
       [0.92040816, 0.94030612, 0.96020408, 0.98010204, 1.        ]])

In [137]:
np.linspace(0.025,1, 40).reshape(5,8)

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [121]:
sveika_saknis = tukstantinis[(tukstantinis ** 0.5) % 1 == 0].reshape(6,-1)

In [122]:
sveika_saknis

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

20\. **(BONUS)**
* Sukurkite vektorių iš sveikų sk. nuo 1 iki 100. Priskirkite kintamąjam.
* Sukurkite Python funkciją, kuri tikrina ar parametruose įvestas sk. yra pirminis. Jeigu pirminis, grąžina True, jei ne, False.
* NumPy nevisada supranta įprastą Python kodą su range'ais ir list'ais, todėl sukurtą funkciją teks vektorizuoti taip : **nauja_funkcija = np.vectorize(jūsų_funkcija)**  .
* Kadangi sąlygos reikšmių traukimui yra *bool* reikšmės, pabandykite vietoje sąlygos įdėti savo vektorizuotą funkciją, ir taip išrinkti pirminius skaičius iš savo vektoriaus
.

In [123]:
masyvas = np.arange(1, 100)


In [127]:
def ar_pirminis(skaicius):
    for i in range(2, skaicius):
        if skaicius % i ==0:
            return False
    else:
        return  True  

In [128]:
n_func = np.vectorize(ar_pirminis)

array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])

In [132]:
masyvas[n_func(masyvas)] #masyvas[n_func(masyvas)]. Tai yra NumPy sintaksė, 
                        #leidžianti pasirinkti tik tuos elementus, kurie tenkina tam tikrą sąlygą.


array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])

In [133]:
print(masyvas[n_func(masyvas)])

[ 1  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83
 89 97]


In [134]:
n_func = np.vectorize(ar_pirminis)
pirminiai_masyvas = masyvas[n_func(masyvas)]

print(pirminiai_masyvas)

[ 1  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83
 89 97]
